### ISSUE TITLE
Remove Powershell Core dependencies

### ISSUE THREAD

**Issue by expertasolutions** [expertasolutions/ExpertaDevOpsToolSet#28]
All tasks that interact with Azure, have to use the Azure Rest API instead of using Azure CLI powershell core script

**Comment by lturmel** [comment]
This is my top priority :)

**Comment by lturmel** [comment]
Now, I start reviewing and refactor the AzureAppInsightDetails task

**Comment by lturmel** [comment]
Tasks remains with Powershell Core dependencies
- ACRAKSAccess
- ACRCredentials
- AzureAppInsight

**Comment by lturmel** [comment]
Remaining tasks with Powershell Core dependencies

ACRAKSAccess - (Done)
ACRCredentials - (Done)
AzureAppInsight - (Done)

**Comment by expertasolutions** [comment]
Fixed and tested properly
