### ISSUE TITLE
Remove deprecated Nodejs Azure-arm*module

### ISSUE THREAD

**Issue by expertasolutions** [expertasolutions/ExpertaDevOpsToolSet#33]
Some Azure node modules are deprecated and already replace by @Azure/arm* module.

Need to be updated it soon as possible

**Comment by lturmel** [comment]
Current Progress:

- ACRCredentials: InProgress
- AzureAppInsigth: Pending
- ManageKeyVaultSecrets: Pending

**Comment by lturmel** [comment]
Current Progress:

ACRCredentials: Done
AzureAppInsigth: Done
ManageKeyVaultSecrets: InValidation

**Comment by expertasolutions** [comment]
Tasks has been validated
